### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'view'

### ISSUE THREAD

**Issue by yiskw713** [4uiiurz1/pytorch-adacos#5]
Thanks for the great implementation. 
I tried to run `python omniglot_train.py --metric adacos`, but the error occurred when validation started.

```
Traceback (most recent call last):
  File "mnist_train.py", line 228, in <module>
    main()
  File "mnist_train.py", line 204, in main
    val_log = validate(args, test_loader, model, metric_fc, criterion)
  File "mnist_train.py", line 98, in validate
    output = metric_fc(feature)
  File "/home/cvrg/.pyenv/versions/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvrg/Documents/pytorch-adacos/metrics.py", line 28, in forward
    one_hot.scatter_(1, label.view(-1, 1).long(), 1)
AttributeError: 'NoneType' object has no attribute 'view'
```

Could you tell me how to validate the model?

**Comment by 4uiiurz1** [comment]
I have fixed.
Please pull and run again!

**Comment by yiskw713** [comment]
Hi, @4uiiurz1.

Thank you for fixing it.
I really appreciate your quick response.

Best Regard,
